var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/services/compliance/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__ab6f3d51._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5f0343b0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_7da8c22c._.js")
R.c("server/chunks/ssr/src_app_ca777385._.js")
R.c("server/chunks/ssr/[root-of-the-server]__df3d79b9._.js")
R.c("server/chunks/ssr/src_app_loading_tsx_7fa31b7f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__75f6154a._.js")
R.c("server/chunks/ssr/_01ab9dcd._.js")
R.c("server/chunks/ssr/_805a4d0c._.js")
R.m(4985)
R.m(63517)
module.exports=R.m(63517).exports
